/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(xcorrelate_engine.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(bdad1a5f471bab2fbe8fa80b91fd8178)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <xcorrelate/xcorrelate_engine.h>
// pydoc.h is automatically generated in the build directory
#include <xcorrelate_engine_pydoc.h>

void bind_xcorrelate_engine(py::module& m)
{

    using xcorrelate_engine    = ::gr::xcorrelate::xcorrelate_engine;


    py::class_<xcorrelate_engine, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<xcorrelate_engine>>(m, "xcorrelate_engine", D(xcorrelate_engine))

        .def(py::init(&xcorrelate_engine::make),
           py::arg("polarization"),
           py::arg("num_inputs"),
           py::arg("output_format"),
           py::arg("num_channels"),
           py::arg("integration"),
           py::arg("omp_threads") = 0,
           D(xcorrelate_engine,make)
        )
        



        ;




}








