/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(xcorrelate_fft_vcf2.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(d0cedbf710ac5bd496011af4b9551d33)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <xcorrelate/xcorrelate_fft_vcf2.h>
// pydoc.h is automatically generated in the build directory
#include <xcorrelate_fft_vcf2_pydoc.h>

void bind_xcorrelate_fft_vcf2(py::module& m)
{

    using xcorrelate_fft_vcf2    = ::gr::xcorrelate::xcorrelate_fft_vcf2;


    py::class_<xcorrelate_fft_vcf2, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<xcorrelate_fft_vcf2>>(m, "xcorrelate_fft_vcf2", D(xcorrelate_fft_vcf2))

        .def(py::init(&xcorrelate_fft_vcf2::make),
           py::arg("vlen"),
           D(xcorrelate_fft_vcf2,make)
        )
        



        ;




}








